strains = [
    {
        "id": 1,
        "name": "Blue Dream",
        "type": "Hybrid",
        "effects": ["Relaxed", "Happy", "Euphoric", "Creative", "Focused"],
        "flavors": ["Berry", "Sweet", "Herbal", "Blueberry", "Vanilla"],
        "thc_content": "18-24%",
        "cbd_content": "0.1-0.2%",
        "description": "A legendary strain known for its balanced effects and sweet berry aroma",
        "growing_time": "9-10 weeks",
        "medical_benefits": ["Stress", "Depression", "Pain", "Headaches"]
    },
    {
        "id": 2,
        "name": "OG Kush",
        "type": "Hybrid",
        "effects": ["Relaxed", "Happy", "Euphoric", "Uplifted", "Sleepy"],
        "flavors": ["Earthy", "Pine", "Woody", "Lemon", "Spicy"],
        "thc_content": "20-25%",
        "cbd_content": "0.2%",
        "description": "A potent strain with a complex aroma profile and strong effects",
        "growing_time": "8-9 weeks",
        "medical_benefits": ["Stress", "Pain", "Anxiety", "Depression"]
    },
    {
        "id": 3,
        "name": "Sour Diesel",
        "type": "Sativa",
        "effects": ["Energetic", "Happy", "Uplifted", "Focused", "Creative"],
        "flavors": ["Diesel", "Citrus", "Earthy", "Pungent", "Sour"],
        "thc_content": "19-25%",
        "cbd_content": "0.1-0.3%",
        "description": "A fast-acting strain that delivers energetic, dreamy cerebral effects",
        "growing_time": "10-11 weeks",
        "medical_benefits": ["Stress", "Depression", "Pain", "Fatigue"]
    },
    {
        "id": 4,
        "name": "Girl Scout Cookies",
        "type": "Hybrid",
        "effects": ["Happy", "Relaxed", "Euphoric", "Uplifted", "Creative"],
        "flavors": ["Sweet", "Mint", "Cookie", "Cherry", "Nutty"],
        "thc_content": "22-28%",
        "cbd_content": "0.2%",
        "description": "A dessert strain with full-body relaxation and cerebral euphoria",
        "growing_time": "9-10 weeks",
        "medical_benefits": ["Stress", "Depression", "Pain", "Appetite"]
    },
    {
        "id": 5,
        "name": "Purple Kush",
        "type": "Indica",
        "effects": ["Relaxed", "Sleepy", "Happy", "Euphoric", "Hungry"],
        "flavors": ["Grape", "Sweet", "Earthy", "Berry", "Floral"],
        "thc_content": "17-22%",
        "cbd_content": "0.1%",
        "description": "A pure indica strain perfect for evening relaxation",
        "growing_time": "8 weeks",
        "medical_benefits": ["Insomnia", "Pain", "Stress", "Muscle Spasms"]
    },
    {
        "id": 6,
        "name": "Green Crack",
        "type": "Sativa",
        "effects": ["Energetic", "Focused", "Happy", "Uplifted", "Creative"],
        "flavors": ["Citrus", "Mango", "Tropical", "Sweet", "Tangy"],
        "thc_content": "15-20%",
        "cbd_content": "0.1%",
        "description": "Sharp energy and focus without nervousness",
        "growing_time": "7-9 weeks",
        "medical_benefits": ["Fatigue", "Stress", "Depression", "ADHD"]
    },
    {
        "id": 7,
        "name": "Wedding Cake",
        "type": "Hybrid",
        "effects": ["Relaxed", "Happy", "Euphoric", "Creative", "Uplifted"],
        "flavors": ["Vanilla", "Sweet", "Pepper", "Creamy", "Nutty"],
        "thc_content": "20-25%",
        "cbd_content": "0.1%",
        "description": "A rich and tangy strain with relaxing and euphoric effects",
        "growing_time": "8-9 weeks",
        "medical_benefits": ["Pain", "Insomnia", "Anxiety", "Depression"]
    },
    {
        "id": 8,
        "name": "Northern Lights",
        "type": "Indica",
        "effects": ["Relaxed", "Sleepy", "Happy", "Euphoric", "Hungry"],
        "flavors": ["Sweet", "Pine", "Spicy", "Earthy", "Woody"],
        "thc_content": "16-21%",
        "cbd_content": "0.1%",
        "description": "A legendary indica known for its resinous buds and peaceful effects",
        "growing_time": "7-9 weeks",
        "medical_benefits": ["Insomnia", "Pain", "Stress", "Depression"]
    },
    {
        "id": 9,
        "name": "Jack Herer",
        "type": "Sativa",
        "effects": ["Happy", "Creative", "Energetic", "Uplifted", "Focused"],
        "flavors": ["Pine", "Woody", "Herbal", "Spicy", "Earthy"],
        "thc_content": "18-23%",
        "cbd_content": "0.1%",
        "description": "A clear-headed, creative strain named after the cannabis activist",
        "growing_time": "8-10 weeks",
        "medical_benefits": ["Stress", "Depression", "Fatigue", "PTSD"]
    },
    {
        "id": 10,
        "name": "Granddaddy Purple",
        "type": "Indica",
        "effects": ["Relaxed", "Sleepy", "Happy", "Euphoric", "Hungry"],
        "flavors": ["Grape", "Berry", "Sweet", "Fruity", "Wine"],
        "thc_content": "17-23%",
        "cbd_content": "0.1%",
        "description": "A complex grape and berry aroma complemented by deep purple flowers",
        "growing_time": "8-11 weeks",
        "medical_benefits": ["Insomnia", "Pain", "Stress", "Appetite"]
    },
    {
        "id": 11,
        "name": "Pineapple Express",
        "type": "Hybrid",
        "effects": ["Happy", "Uplifted", "Energetic", "Creative", "Focused"],
        "flavors": ["Pineapple", "Tropical", "Sweet", "Citrus", "Cedar"],
        "thc_content": "19-25%",
        "cbd_content": "0.1%",
        "description": "A tropical-flavored strain that provides a long-lasting energetic buzz",
        "growing_time": "7-8 weeks",
        "medical_benefits": ["Stress", "Depression", "Pain", "Fatigue"]
    },
    {
        "id": 12,
        "name": "White Widow",
        "type": "Hybrid",
        "effects": ["Happy", "Relaxed", "Euphoric", "Energetic", "Creative"],
        "flavors": ["Earthy", "Woody", "Pine", "Sweet", "Floral"],
        "thc_content": "18-25%",
        "cbd_content": "0.2%",
        "description": "A balanced hybrid known for its white crystal resin",
        "growing_time": "8-9 weeks",
        "medical_benefits": ["Stress", "Depression", "Pain", "Lack of Appetite"]
    },
    {
        "id": 13,
        "name": "AK-47",
        "type": "Hybrid",
        "effects": ["Happy", "Relaxed", "Uplifted", "Creative", "Focused"],
        "flavors": ["Earthy", "Pine", "Woody", "Skunk", "Sweet"],
        "thc_content": "13-20%",
        "cbd_content": "0.1%",
        "description": "A mellow strain that delivers a steady and long-lasting cerebral buzz",
        "growing_time": "7-9 weeks",
        "medical_benefits": ["Stress", "Depression", "Pain", "Anxiety"]
    },
    {
        "id": 14,
        "name": "Durban Poison",
        "type": "Sativa",
        "effects": ["Energetic", "Focused", "Creative", "Uplifted", "Happy"],
        "flavors": ["Sweet", "Pine", "Earthy", "Spicy", "Anise"],
        "thc_content": "17-26%",
        "cbd_content": "0.02%",
        "description": "A pure African sativa that's known for its sweet smell and energetic high",
        "growing_time": "8-9 weeks",
        "medical_benefits": ["Fatigue", "Depression", "Stress", "Anxiety"]
    },
    {
        "id": 15,
        "name": "Bubba Kush",
        "type": "Indica",
        "effects": ["Relaxed", "Sleepy", "Happy", "Hungry", "Euphoric"],
        "flavors": ["Coffee", "Earthy", "Woody", "Sweet", "Chocolate"],
        "thc_content": "14-22%",
        "cbd_content": "0.1%",
        "description": "A heavy indica hybrid that's perfect for night time use",
        "growing_time": "8-9 weeks",
        "medical_benefits": ["Insomnia", "Pain", "Stress", "Lack of Appetite"]
    }
]